name: cucumber_wire
description: Write cucumber test definitions in dart and run them using the cucumber wire protocol.
version: 0.1.0
author: Eric Schneller <eric@schnellers.name>
homepage: https://github.com/eredo/cucumber_wire

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  webdriver: ^2.0.0
  test: ^1.3.0
  watcher: ^0.9.0
  path: ^1.6.0
  args: ^1.5.0
  cli_util: ^0.1.3
  meta: ^1.1.0
  matcher: ^0.12.0

dev_dependencies:
  mockito: ^3.0.0
  dart_coveralls: ^0.6.0
  pedantic: ^1.1.0