name: cucumber_wire

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  webdriver: ^2.0.0
  test: ^1.3.0
  watcher: ^0.9.0
  path: ^1.6.0
  args: ^1.5.0
  cli_util: ^0.1.3

dev_dependencies:
  mockito: ^3.0.0